# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 12
    - nodejs_version: 14

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install eslint eslint-plugin-import
  - npm install --ignore-scripts --force

test_script:
  - node --version
  - npm --version
  - npm test
